Repository GSG-CF05/smart-phone-store-team2, pull requests merged in 2022-03, with the labels that each got.

#3 creating the file structure of the app and adding the bassic structur…
  aboutPage/about.css
  aboutPage/about.html
  aboutPage/about.js
  cartPage/cart.css
  cartPage/cart.html
  cartPage/cart.js
  index.html
  productsPage/products.css
  productsPage/products.html
  productsPage/products.js
  style.css
Labels: approved

#19 create the home page javaScript file
  file.js
Labels: awaiting-review

#22 Create heading to products page
  images/Search.svg
  productsPage/products.css
  productsPage/products.html
Labels: approved

#23 create the header of the home page and add the drawer and do the medi…
  .vscode/settings.json
  file.js
  index.html
  style.css
Labels: approved

#29 create the splash of the home page and add the function for it
  file.js
  index.html
  style.css
Labels: approved

#30 Create layout products page
  productsPage/products.css
  productsPage/products.html
Labels: approved

#24 Create the header for cart page
  cartPage/cart.css
  cartPage/cart.html
  cartPage/cart.js
Labels: approved

#32 create the top brands section for home page and change
  file.js
  index.html
  style.css
Labels: awaiting-review

#27 create the body for the about page and adding the functionality to fet…
  aboutPage/about.css
  aboutPage/about.html
  aboutPage/about.js
Labels: approved

#34 Create the lastest product section
  file.js
  images/addToCart.png
  index.html
  style.css
Labels: approved

#36 delete .vscode file
  .vscode/settings.json
  productsPage/products.css
Labels: done

#40 create fetch function in prouducts page , The value of the Fitch is t…
  productsPage/products.css
  productsPage/products.html
  productsPage/products.js
Labels: done

#26 Add cart body
  cartPage/cart.css
  cartPage/cart.html
  cartPage/cart.js
Labels: awaiting-review

#43 create function setItemLocal in products page
  productsPage/products.js
Labels: awaiting-review

#44 creaing the readme file and adding its required information
  README.md
Labels: approved

#41 making the home page images slider responsive
  index.html
  style.css
Labels: awaiting-review

#37 making the about page responsive
  aboutPage/about.css
  aboutPage/about.html
Labels: awaiting-review

#46 create function search that enables the user to search for any phone …
  cartPage/cart.html
  productsPage/products.js
Labels: done

#49 Some improvements to the responsiveness of the page with some additions
  file.js
  index.html
  style.css
Labels: awaiting-review

#50 finalizing the design of the about page
  aboutPage/about.css
  aboutPage/about.html
  aboutPage/about.js
Labels: awaiting-review

#54 adding the live link
  README.md
Labels: approved

#56 edit link path
  aboutPage/about.css
  aboutPage/about.html
  file.js
  images/logo.svg
  index.html
  style.css
Labels: awaiting-review

#58 edit path
  file.js
  productsPage/products.html
Labels: awaiting-review
